### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by AlbanT** [corneliusmunz/legoino#13]
According to the README the LED colours are:

> Available colors are: BLACK, PINK, PURPLE, BLUE, **LIGHT_BLUE**, CYAN, GREEN, YELLOW, ORANGE, RED, WHITE

But **LIGHT_BLUE** should have been **LIGHTBLUE**

**Comment by corneliusmunz** [comment]
@AlbanT Thanks for reporting that. I have corrected it with the latest commit: https://github.com/corneliusmunz/legoino/commit/edc40fa058e640bf455411be0708832a0e13b093
