### ISSUE TITLE
Some issue sconnecting for the first time

### ISSUE THREAD

**Issue by AlbanT** [corneliusmunz/legoino#14]
Not sure why but my ESP32 won't connect if the Movehub has been turned of for a longer period of time.
When I connect it first to the Powered Up app on my phone and then close the app again the ESP connects without any problems. But when I try to do it without "waking" the hub (Boost Movehub) with the app the ESP won't connect.
Does this sound familiar?

**Comment by corneliusmunz** [comment]
@AlbanT Up to now that don't sound familiar to me. I will check it but normally during testing and using the lib i do not connect to the app and directly connect the hub to the esp32 controller. My procedure is:
1) Power on the esp32 controller
2) Power on the hub by pressing the hub button

Sometimes the connection does not work an i have to press the reset button on my esp32 board. 

I try to check the behaviour if i connect the hub to the app and then to the esp32
