### ISSUE TITLE
Support for Control+

### ISSUE THREAD

**Issue by jabrena** [corneliusmunz/legoino#16]
Hi, 

Is the library compatible with LEGO control+?

**Comment by corneliusmunz** [comment]
Hi @jabrena ! I‘m working on the support for Control+ but it will take some time. But in the meanwhile you can use the work of the following Pull-Request. I will not merge it because I will structure it a little bit different but it works: https://github.com/corneliusmunz/legoino/pull/6

**Comment by corneliusmunz** [comment]
@jabrena With the new release version 0.7.0 the support of the Control+ Hubs are added: https://github.com/corneliusmunz/legoino/releases/tag/0.7.0

**Comment by jabrena** [comment]
Many thanks,

I received the board, but I was on holidays and I could deploy any code in the board. Next week, I will give you feedback.

Cheers
