### ISSUE TITLE
NodeMCU ESP8266

### ISSUE THREAD

**Issue by lokerhp** [corneliusmunz/legoino#28]
Hello,

I'm using a NodeMCU ESP8266 and i'm attempting to use legoino but it fails. So my question is, is it possible to use legoino on a NodeMCU 8266?

Greetings,

Niek

**Comment by corneliusmunz** [comment]
HI @lokerhp! Unfortunately this will not work because the ESP8266 has no build in Bluetooth and the used Bluetooth library does only support ESP32 boards.
Cheers, Cornelius

**Comment by lokerhp** [comment]
Hey, i just bought a ESP32 And now it works, thanks for your help 👍

**Comment by corneliusmunz** [comment]
@lokerhp Cool! Nice to hear that 👍
