### ISSUE TITLE
error example lego trainhub

### ISSUE THREAD

**Issue by Timo-VB** [corneliusmunz/legoino#82]
It doesn't work i am getting errors if i want to upload the example.

**Comment by uwemon** [comment]
Hello, you are using NimBLE-Arduino Library 2.0.0. Go back to version 1.4.3. and try again.

Best regards

Uwe

**Comment by Timo-VB** [comment]
It still doesn't work. He is giving the same error.

**Comment by corneliusmunz** [comment]
Hi @Timo-VB There is indeed an error when using the latest Nimble Library. If you have problems even after downgrading to NimBLE-Arduino 1.4.3, just give me some more details about the error.

Which development library have you used (Arduino IDE or PlatformIO)?
Which board are you using 
Can you send me the detailed error?

Best regards,
Cornelius

Maybe I have time during the Christmas holidays to prepare the library for the NimBLE-Arduino update

**Comment by Timo-VB** [comment]
Hello. I am using Arduino IDE.
I have already installed NimBLE-arduino 1.4.3 and I have already reinstalled legoino.
This is the error code:
In file included from C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.cpp:11:
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:29:15: error: 'string' in namespace 'std' does not name a type
   29 |   static std::string ColorStringFromColor(Color color);
      |               ^~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:16:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   15 | #include "Lpf2HubConst.h"
  +++ |+#include <string>
   16 | 
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:30:15: error: 'string' in namespace 'std' does not name a type
   30 |   static std::string ColorStringFromColor(int color);
      |               ^~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:30:10: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   30 |   static std::string ColorStringFromColor(int color);
      |          ^~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.cpp:39:6: error: 'string' in namespace 'std' does not name a type
   39 | std::string LegoinoCommon::ColorStringFromColor(Color color)
      |      ^~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.cpp:12:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   11 | #include "LegoinoCommon.h"
  +++ |+#include <string>
   12 | 
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.cpp:48:6: error: 'string' in namespace 'std' does not name a type
   48 | std::string LegoinoCommon::ColorStringFromColor(int color)
      |      ^~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.cpp:48:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   48 | std::string LegoinoCommon::ColorStringFromColor(int color)
      | ^~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.cpp:101:10: error: no declaration matches 'uint32_t LegoinoCommon::ReadUInt32LE(uint8_t*, int)'
  101 | uint32_t LegoinoCommon::ReadUInt32LE(uint8_t *data, int offset = 0)
      |          ^~~~~~~~~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:27:23: note: candidate is: 'static unsigned int LegoinoCommon::ReadUInt32LE(uint8_t*, int)'
   27 |   static unsigned int ReadUInt32LE(uint8_t *data, int offset);
      |                       ^~~~~~~~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:17:7: note: 'class LegoinoCommon' defined here
   17 | class LegoinoCommon
      |       ^~~~~~~~~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.cpp:107:9: error: no declaration matches 'int32_t LegoinoCommon::ReadInt32LE(uint8_t*, int)'
  107 | int32_t LegoinoCommon::ReadInt32LE(uint8_t *data, int offset = 0)
      |         ^~~~~~~~~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:28:21: note: candidate is: 'static int LegoinoCommon::ReadInt32LE(uint8_t*, int)'
   28 |   static signed int ReadInt32LE(uint8_t *data, int offset);
      |                     ^~~~~~~~~~~
C:\Users\timov\OneDrive - Sigo\thuislaptop\Documenten\Arduino\libraries\Legoino\src\LegoinoCommon.h:17:7: note: 'class LegoinoCommon' defined here
   17 | class LegoinoCommon
      |       ^~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

**Comment by corneliusmunz** [comment]
Hi @Timo-VB ! I have tried to reproduce the issue on my system and I think I have found the error. The error ist related to the ESP32 library which has the current version 3.x.x  In the time where I have developed the library, the version 2.x.x was available. In the version change a breaking change was introduced about string handling: https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html 

So as long as I have no new version, you can

 try to compile the example sketches with the latest 2.x.x version of the esp32 framework (2.0.17) With this version I can compile without any errors and with the 3.x.x versions I got the same error as you. 

Can you please give this a try? You can change the ESP32 framework version as follows:

<img width="544" alt="arduino_esp32_version_selection" src="https://github.com/user-attachments/assets/45d25535-f424-4243-8aba-78e8cb9c0e67">

**Comment by Timo-VB** [comment]
It works! Thank you very very much!

Best regards,
Timo-VB
